[General]
network = PCN
fname-append-host = true
result-dir = results

# Use a small topology and workload for quick tests
*.netBuilder.topologyFile = "../topologies/topology"
#*.netBuilder.workloadFile = "../workloads/merchant-workload.txt"
*.netBuilder.workloadFile = "../workloads/random-workload.txt"

# Default behaviour for all nodes
#**.role = "honest"
#**.failureProbability = 0
#**.attackDestination = ""

# Configure node1 as an unreliable user with random failures
*.node1.role = "unreliable"
*.node1.failureProbability = 0.15
